### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by alsoGAMER** [Arxdust/pihole2telegram#1]
```
$ python3 pihole2telegram.py
Traceback (most recent call last):
  File "pihole2telegram.py", line 2, in <module>
    from telegram.ext import CommandHandler
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/__init__.py", line 25, in <module>
    from .callbackcontext import CallbackContext
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/callbackcontext.py", line 21, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/usr/local/lib/python3.7/dist-packages/telegram/__init__.py)
```

**Comment by FleuryK** [comment]
Hello, i have found a solution which I am torn my hair for hours.
I've forked this project at https://github.com/FleuryK/pihole2telegram/.

Download pihole2telegram.py (other files is not modified) and put it on your server.

This file pihole2telegram.py on this GitHub works for an older version for Telegram. With this file on my GitHub, he works (at the moment) with latest modules for python.

Don't hesitate to open a issue on my GitHub if you still have problems.

Cordially.
